[build-system]
requires = ["setuptools>=80", "setuptools-scm>=9"]
build-backend = "setuptools.build_meta"

[project]
name = "mosaic-categorizer"
authors = [
    { name = "Théo Jolivel", email = "theo.jolivel@inria.fr" },
    { name = "François Tessier" },
]
description = "MOSAIC is an automatic I/O patterns categorizer"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["categorizer", "classifier", "pattern"]
license = "BSD-3-Clause"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research"
]
dependencies = [
    "darshan~=3.5.0",
    "kaleido~=1.3.0",
    "matplotlib~=3.11.1",
    "numpy~=2.4.6",
    "pandas~=3.0.5",
    "plotly~=6.9.0",
    "seaborn~=0.13.2",
    "scikit-learn~=1.9.0",
    "tqdm~=4.70.0",
    "ftio-hpc~=0.0.9",
    "palettable~=3.3.3"
]
dynamic = ["version"]

[tool.setuptools]
py-modules = []
ext-modules = [
    { name = "mosaic.darshanv2logutils", sources = ["mosaic/tef_generators/darshan_python_c_module/darshan-logutils.c", "mosaic/tef_generators/darshan_python_c_module/darshan_logutils_py.c"], libraries = ["z", "bz2"] }
]

[tool.setuptools_scm]

[tool.setuptools.packages]
find = {where = ["."]}

[tool.setuptools.package-dir]
"" = "."